/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter API for testing (JUnit 5)
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    
    // Runtime engine for running the JUnit tests
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
    
    // Optionally, use the JUnit Platform Launcher (for IDE support)
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.7.0'

    // If you're using Google Guava (as per your example)
    implementation 'com.google.guava:guava:30.1-jre'
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "junitatm.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
